### ISSUE TITLE
API Components

### ISSUE THREAD

**Issue by buckyroberts** [buckyroberts/Vataxia-Frontend#3]
Build pages and components for all existing API endpoints:

- login page
- posts (with replies)
- private messages
- profiles
- update password
- users

**Comment by buckyroberts** [comment]
Use this for user settings section: https://v4-alpha.getbootstrap.com/examples/dashboard/#

**Comment by designviacode** [comment]
Hey @buckyroberts are you looking for contributions... I'm a frontend developer, I would be interested in working on this.. 😉

**Comment by buckyroberts** [comment]
@designviacode Yes feel free, right now I am still just working on the basic designs/layout. In a few days I am going to start hooking everything up the the API
